version: "3.6"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: review

  redis:
    image: redis
    ports:
      - "6379:6379"
    